brainstormforce/ultimate-addons-for-beaver-builder-lite

- classes/class-uabb-admin-settings.php
- includes/admin-settings-general.php
- readme.txt
Changes as per w.org reviews regarding Sanitization and Validation
> Org review

- bb-ultimate-addon.php
- classes/class-ui-panel.php
- fields/_config.php
- readme.txt
FIxed beaver builder v1.10 compatibility
> Fixed bb v1.10 compatibility issue

- bb-ultimate-addon.php
> Version constant updated

- modules/image-separator/css/frontend.css
- readme.txt
Fixed scroll bar issue on small devices
> Fixed scroll bar issue of image separator module and changelog updated

- modules/flip-box/flip-box.php
- modules/image-icon/image-icon.php
- modules/image-separator/image-separator.php
- modules/info-list/info-list.php
- modules/info-table/info-table.php
- modules/ribbon/ribbon.php
- modules/slide-box/slide-box.php
- modules/uabb-button/uabb-button.php
Added connection in fields of modules.
> Added connection in fields of modules

- README.md
- bb-ultimate-addon.php
- package.json
- readme.txt
Added Beaver Themer support, Use modules from ultimate beaver to create dynamic page layouts with Beaver Themer.
> Version bump v1.1.0

- classes/class-uabb-admin-settings.php
- classes/class-uabb-helper.php
- modules/flip-box/flip-box.php
- modules/image-icon/image-icon.php
- modules/image-separator/image-separator.php
- modules/info-list/info-list.php
- modules/info-table/info-table.php
- modules/ribbon/ribbon.php
- modules/slide-box/slide-box.php
- modules/spacer-gap/spacer-gap.php
- modules/uabb-button/uabb-button.php
- modules/uabb-separator/uabb-separator.php
> Beaver Builder - Version 2 compatibility

- .travis.yml
- README.md
- bb-ultimate-addon.php
- readme.txt
Fixed: Global settings compatibility with Astra theme.
> Update readme.txt and change version to 1.2.1

- classes/class-uabb-init.php
- classes/class-uabb-wpml.php
- classes/wpml/class-wpml-uabb-infolist.php
WPML Compatibility for UABB modules
> WPML Compatibility

- README.md
- modules/uabb-heading/includes/frontend.css.php
- readme.txt
* Fixed Heading module Title mobile font size not working
> fix: heading module mobile font issue

- classes/class-uabb-helper.php
- Added Latest Premium modules, WooModules and updated the tag as required.
> Add pro modules in WordPress Dashboard

- README.md
- modules/uabb-heading/includes/frontend.css.php
- modules/uabb-heading/uabb-heading-bb-2-2-compatibility.php
- modules/uabb-heading/uabb-heading-bb-less-than-2-2-compatibility.php
- readme.txt
- Improvement: Added Heading Background Color and Padding setting options in the Heading module.
> Improvement: Added Heading Background Color and Padding setting options in Heading module.

- README.md
- modules/info-list/includes/frontend.css.php
- readme.txt
Fixed: PHP warnings in Info List module
> Fixed: PHP warnings in Info List module

- bb-ultimate-addon.php
Added missing prefix for the function.
> Added function prefix

- README.md
- readme.txt
> Updated changelog.txt

- README.md
- readme.txt
- Updated Tested Upto tag in readme files
> Updated Tested Upto tag in readme files

- README.md
- bb-ultimate-addon.php
- classes/class-uabb-admin-settings.php
- classes/class-uabb-helper.php
- readme.txt
Old Logic - Check if at least 5 posts are published using UABB
New Logic - Check if the UABB - Lite plugin is installed over 15 days.
> Changed logic to display Review notice

- classes/class-uabb-helper.php
-  Added new modules list with respective tags
- https://share.getcloudapp.com/nOuedpkB
- Added latest modules and tags
Yes
> Update module list with Tags

- modules/uabb-star-rating/includes/frontend.css.php
- modules/uabb-star-rating/includes/frontend.php
Issue - https://share.getcloudapp.com/GGuonAP2
Fixed - https://share.getcloudapp.com/YEupgdD5
> Fix - Star Rating: Issue with Inline Layout and Justify alignment

- README.md
- admin/bsf-analytics/assets/css/minified/style.min-rtl.css
- admin/bsf-analytics/assets/css/minified/style.min.css
- admin/bsf-analytics/assets/css/unminified/style-rtl.css
- admin/bsf-analytics/assets/css/unminified/style.css
- admin/bsf-analytics/class-bsf-analytics-stats.php
- admin/bsf-analytics/class-bsf-analytics.php
- classes/class-uabb-init.php
- readme.txt
> New: Users can now share non-personal usage data to help us test and develop better products.

- README.md
- readme.txt
> WordPress 5.5 Compatibility 

- README.md
- readme.txt
> WordPress 5.6 compatibility

- README.md
- modules/uabb-heading/includes/frontend.php
- readme.txt
- Improvement: Heading - Parsed the description in the heading in a better way by using `$wp_embed->autoembed`.
> Improve heading description output

- README.md
- bb-ultimate-addon.php
- modules/flip-box/includes/frontend.js.php
- modules/slide-box/js/settings.js
- modules/uabb-heading/includes/frontend.php
- readme.txt
* Improvement: Compatibility with WordPress 5.7.
* Improvement: Heading - Parsed the description in the heading in a better way by using `$wp_embed->autoembed`.
> Next release to master

- README.md
- bb-ultimate-addon.php
- modules/flip-box/includes/frontend.css.php
- readme.txt
Fixed: Flip Box - Repeat setting not working for Front and Back Background Images.
> Fixed: Flip Box - Repeat setting not working for Front and Back Background Images.

- README.md
- bb-ultimate-addon.php
- modules/uabb-heading/includes/frontend.css.php
- readme.txt
Fixed: Heading - Resolved PHP warning for undefined property.
PHP Warning:  Undefined property: stdClass::$img_border_width in C:\laragon\www\wordpress\wp-content\plugins\ultimate-addons-for-beaver-builder-lite\modules\uabb-heading\includes\frontend.css.php on line 374
> Fixed: Heading - Resolved PHP warning for undefined property.

- .github/workflows/push-asset-readme-update.yml
- README.md
- readme.txt
No issues were found
Updated tested up to tag to 6.1
> WordPress 6.1 compatibility

- README.md
- assets/js/uabb-admin.js
- bb-ultimate-addon.php
- classes/class-uabb-admin-settings.php
- classes/class-uabb-iconfonts.php
- readme.txt
- Add nonce check for reload icons ajax call.
> Add nonce check for reload icon ajax call

- README.md
- assets/js/uabb-cloud-templates.js
- bb-ultimate-addon.php
- classes/class-uabb-admin-settings.php
- classes/class-uabb-cloud-templates.php
- includes/admin-settings-template-cloud.php
- readme.txt
- Added nonce verification for fetching cloud templates AJAX action
> Added nonce verification for fetching cloud templates AJAX action

- README.md
- readme.txt
next-release was not updated to master
> Up-to-date Next release 

- README.md
- modules/ribbon/includes/frontend.php
- readme.txt
> Next release - Update WP 6.8
